### ISSUE TITLE
Currently two players cannot play together from 2 different computers

### ISSUE THREAD

**Issue by erilyth** [sugarlabs/sugarchess#2]
When we invite another user to the activity, then they can join but after they join they just play independently, there is no collaboration of any kind. 
Is there anything else the two users can do together? If not then should the invite option be disabled by using max_participants=0, and just removing the tubes code or should the functionality be added?

**Comment by samdroid-apps** [comment]
Reproduced on fc24 sugar-build over salut (tubes supported)

Log suggests that it is an error in the collab implementation.

```
1452310993.096024 DEBUG sugar3.presence.buddy: Buddy.__init__
1452310993.099375 DEBUG root: Activity.__joined_cb True
Traceback (most recent call last):
  File "/home/saam/sugar-build/activities/sugarchess/GNUChessActivity.py", line 784, in _joined_cb
    self._new_tube_common(False)
  File "/home/saam/sugar-build/activities/sugarchess/GNUChessActivity.py", line 788, in _new_tube_common
    if self._shared_activity is None:
AttributeError: 'GNUChessActivity' object has no attribute '_shared_activity'
Traceback (most recent call last):
  File "/home/saam/sugar-build/activities/sugarchess/GNUChessActivity.py", line 784, in _joined_cb
    self._new_tube_common(False)
  File "/home/saam/sugar-build/activities/sugarchess/GNUChessActivity.py", line 788, in _new_tube_common
    if self._shared_activity is None:
AttributeError: 'GNUChessActivity' object has no attribute '_shared_activity'
```

**Comment by quozl** [comment]
@tonadev, this might be interesting, as it may look familiar.
